feat(LB Wind Rose): Update with different frequency visualization.
ladybug-tools/ladybug-grasshopper pull request #123
Opened 2020-10-28 05:55 UTC by saeranv

@chriswmackey, @ayezioro 
cc @mostaphaRoudsari 

This is the updated Windrose with frequencies visualized by size of the windrose bar, and with the frequencies and averages as an output in the component (credit to Chris for help on that).  

![image](https://user-images.githubusercontent.com/1685956/97392555-6efc2700-18b8-11eb-933c-32c64925faa2.png)

While I was working on the frequencies, I also found that the frequencies, averages, and distribution calculated by the legacy component is slightly different from what I have in this updated windrose: 

Averages
The legacy component included calm (zero) hours in its calculation of average velocity per direction. This seems to be a logic error since zero hours by definition have no direction and should be excluded. EPWs also seem to classify all zero hours in the North direction, so the north average is a lot lower then it should be.   

Frequencies 
Here, the legacy component doesn't include zero hours for its calculation of hours per direction, but to compute it's percentage, it divides the hours by the total wind hours (including zero hours). Again, this seems to be a logic error, especially since as you would expect, the sum of the frequencies don't add up to 100 as they should.

For this updated component, I excluded all calm hours from the average and frequency calculation (and mentioned this explicitly in the docstrings). Let me know if there's a problem in my reasoning. If not, I think this should complete the windrose updates. 

S

2020-10-28 06:16 UTC, ayezioro commented
Hi @saeranv,
Thanks for the updates you are doing in this so important component.
For the sake of the discussion let me challenge your login for the frequency (and maybe also the averages).
Let's assume a (very) theoretical case where you have only 1 hour, from all 8760, with a velocity bigger than 0. Say the value is 20 m/s.
What will be the frequency value the component is giving? 100% or something else?
What will be the average? 20 or something else?
If the answers are 100 and 20 i think this is an error, a logic one. I don't know how these statistics should be calculated, though. Wish i know.
Makes sense or i'm completely wrong?

-A.

2020-10-29 15:30 UTC, chriswmackey reviewed
Looks good to me but there are 2 things we will need before we can merge:

1. [This PR on ladybug-core](https://github.com/ladybug-tools/ladybug/pull/367) needs to be merged first.
2. You need to export the Wind Rose with the latest "LB Export UserObject" component, which will ensure that we get the JSON representation of the component gets updated here on the repo so that ladybug-blender can generate a new windrose component.

FYI, you can use the ignore tag on the "LB Export UserObject" to bypass the semantic verion check:
![image](https://user-images.githubusercontent.com/5567574/97595592-36546e80-19da-11eb-9007-162738834c46.png)

2020-10-29 15:30 UTC, chriswmackey commented on ladybug_grasshopper/src/LB Wind Rose.py
> +#        filt_wind_dir = _wind_direction.filter_by_pattern(pattern)
If we don't want this, then it should be removed before merging

2020-10-29 15:30 UTC, chriswmackey commented on ladybug_grasshopper/src/LB Wind Rose.py
> +ghenv.Component.Message = '1.0.2'
The version incrementing does not seem correct here. It should probably be 1.0.1.

2020-10-29 15:49 UTC, saeranv commented on ladybug_grasshopper/src/LB Wind Rose.py
> +#        filt_wind_dir = _wind_direction.filter_by_pattern(pattern)
@chriswmackey This is something I forgot to raise in my PR comments. I noticed you are filtering out the wind directions that have zero hours here. I am doing this within the windrose module. Is there a reason you think it needs to be done in the GH component? If it's redundant I agree let's delete it.

2020-10-29 16:29 UTC, saeranv commented
> Hi @saeranv,
> Thanks for the updates you are doing in this so important component.
> For the sake of the discussion let me challenge your login for the frequency (and maybe also the averages).
> Let's assume a (very) theoretical case where you have only 1 hour, from all 8760, with a velocity bigger than 0. Say the value is 20 m/s.
> What will be the frequency value the component is giving? 100% or something else?
> What will be the average? 20 or something else?
> If the answers are 100 and 20 i think this is an error, a logic one. I don't know how these statistics should be calculated, though. Wish i know.
> Makes sense or i'm completely wrong?

@ayezioro these are good points. 

I would argue for the average values, 20 m/s is indeed the correct average. This is because both we are only defining average speed per direction. Since 0 m/s has no wind direction, it doesn't contribute to the average. We have arbitrarily split all zero hours by the number of directions for the purpose of the calm rose visualization, but in reality, those zero hours have no direction associated with them. 

Your example for frequencies is not as simple to reconcile, since the total wind hours we use to calculate the percent is somewhat ambiguous. One thing I realized is that your argument (frequency should be 1 / 8760) in fact was what the legacy component was doing, and I now understand what the original reasoning behind it was. However, I would argue this is still wrong from a rigorous definition of frequencies (i.e defined here https://en.wikipedia.org/wiki/Frequency_(statistics)). The reason is that the 8759 hours (or 8759 / 8760 fraction) cannot be incorporated into the frequency distribution calculation since it has no direction. That is, if we plotted a histogram for each orientation (let's say 0 to 360 with intervals of 90) - there's no bin where the rest of the hours would show up - since zero hours have no direction. Another way to think about it is that the area of the normalized histogram needs to add up to 1, which would not be the case here. 

That being said, it may be better to just output the number of hours, and not the percents, which gives flexibility for users to compute either way.

2020-10-29 17:04 UTC, ayezioro commented
Hi @saeranv,
I'll give you another example. There are places that have standards requiring some maximal performance of the wind. For instance for environmental analysis they ask that for "Dangerous winds" (Say 15 m/s, not sure this is the number), they can't occur more than 3% of the time (not sure either about the %, but as an example). So i'm not sure how can i get this "of the time" calculated. The more zero hours you have the percentage of the dangerous wind will increase, right? If i'm right it doesn't seem to me correct. What you say makes absolute sense for me but the above makes me worried. Probably your solution of outputting the number of hours is fine' providing also the number of non-zero hours too.
What do you think?
-A.

2020-10-29 17:18 UTC, saeranv commented
@ayezioro 

I see, so in that case, the direction of wind doesn't matter so (from your previous example) it would be 1/ 8760. In our case, it's only because we are splitting the wind hours into directions bins that we are essentially getting trapped by a logic error:  the set of zero winds are the complement of the set of winds with direction - there's no way to meaningfully compare them together. 

I agree, a good compromise seems to be outputting the hours per direction plus a zero ours output.

2020-10-30 01:30 UTC, saeranv commented
@ayezioro, here's the updates with what we've discussed: 

![image](https://user-images.githubusercontent.com/1685956/97649397-9c1e1600-1a2d-11eb-959e-da076f97216f.png)

And here's the way the tool hint describes these values:
```
        freq_by_dir: A list of frequency _data values (bound by max_freq_lines_) for each wind 
            direction as number of hours. This does not include calm hours since they 
            do not have any direction associated with their values. This hourly count can be 
            divided by the total wind hours to calculating frequency as a percentage.
        avg_by_dir: A list of average _data values (bound by max_freq_lines_) with one value 
            for each wind direction. This does not include calm hours since they do not have 
            any direction associated with their values. 
        calm_hours: The number of hours with calm wind speeds. Only returns a value if the input 
            _data is wind speed. 
```

@chriswmackey, I made the changes you suggested. 

Let me know if there's anything else that needs to be done.

2020-10-30 04:08 UTC, ayezioro commented
Thanks @saeranv,
Looks good.
-A.

2020-11-01 17:33 UTC, chriswmackey commented on ladybug_grasshopper/src/LB Wind Rose.py
> +#        filt_wind_dir = _wind_direction.filter_by_pattern(pattern)
If you are now doing this inside the wind rose class then, yes, let's delete it.

2020-11-03 00:31 UTC, chriswmackey requested changes

2020-11-03 00:31 UTC, chriswmackey commented on ladybug_grasshopper/src/LB Wind Rose.py
> +            the statement or period operations input to this component.
I am worried that the component is getting too large and that we are succumbing to the temptation to make the component output everything just because we can.  Can we remove the `avg_by_dir` and `freq_by_dir` because people can easily drive these from the `histogram`. Also, I think it's implied that the output is data so you don't need to call it `histogram_data`.

Lastly, if you are going to spit the entire histogram out of the component into the Grasshopper UI, please wrap it as an object so that it doesn't increase the component run time.  You can see an example here for how to wrap the data in a way that people can use the ["LB Deconstruct Matrix"](https://github.com/ladybug-tools/ladybug-grasshopper/blob/master/ladybug_grasshopper/src/LB%20Deconstruct%20Matrix.py) to get the data if they really need it to be spit out into the UI:
https://github.com/ladybug-tools/ladybug-grasshopper/blob/master/ladybug_grasshopper/src/LB%20Direct%20Sun%20Hours.py#L129

2020-11-03 00:32 UTC, chriswmackey commented on ladybug_grasshopper/src/LB Wind Rose.py
> +            the statement or period operations input to this component.
I'm also open to removing other outputs that can be easily derived from the other data if you are particularly attached to one of these.

2020-11-03 01:14 UTC, chriswmackey commented on ladybug_grasshopper/src/LB Wind Rose.py
> +            the statement or period operations input to this component.
Actually, I can see that this really isn't increasing the overall size of the component so I guess it's ok. My comment about wrapping the histogram data into an object still holds, though.  This will keep the component running efficiently.

2020-11-03 02:16 UTC, saeranv commented on ladybug_grasshopper/src/LB Wind Rose.py
> +            the statement or period operations input to this component.
@chriswmackey I agree with removing the speeds and frequencies since we can derive it from the histogram now. I think those are the main outputs that are easy to derive from histogram (requires adding one GH component).

2020-11-03 02:33 UTC, saeranv commented
This is how users can compute averages and frequencies now:

![image](https://user-images.githubusercontent.com/1685956/97944484-d13ea700-1d52-11eb-8b19-fdc6217fa56e.png)

Personally this is the version of the Wind Rose that I would want to use. It's flexible enough for any calculations, while still remaining lightweight.

2020-11-04 23:35 UTC, chriswmackey approved these changes
Looks good, @saeranv . I just merged your ladybug-core PR and we can merge this one once the releases of the whole core library dependency tree is complete.

2020-11-04 23:46 UTC, saeranv commented
@chriswmackey Awesome thanks!

2020-11-05 02:46 UTC, merged

2020-11-07 16:17 UTC, ayezioro commented
Hi @saeranv,
I have a thought/wish for the title of the wind rose when you ask for frequency. It should say Wind Frequency [%] (instead of wind speed [m/s]).
Also the legend should show [%] instead [m/s] as the units.
I know that it can be possible to change afterwards, but more easy to make it straight inside the component.
Thanks,
-A.